sysdig: upgrade 0.28.0 -> 0.39.0
Upgrade sysdig to solve build failure after upgrading valijson to 1.1.0.

1.Changelog
  https://github.com/draios/sysdig/releases/tag/0.39.0

2.Update 0001-cmake-Pass-PROBE_NAME-via-CFLAGS.patch for 0.39.0

3.Remove following patches as merged upstream
  0001-Add-cstdint-for-uintXX_t-types.patch
  0001-libsinsp-fix-build-with-gcc-15.patch

4.Add 0001-Avoid-duplicate-operations-of-add_library.patch to fix do_configure errors
  -- Existing strlcat found, will *not* use local definition
  CMake Error at falcosecurity-libs/userspace/libscap/CMakeLists.txt:64 (add_library):
    add_library cannot create target "scap_error" because another target with
    the same name already exists.  The existing target is a static library

5.Add CMAKE option -DBUILD_SYSDIG_MODERN_BPF=OFF to fix bpf header file not found issue
  sysdig/0.39.0/recipe-sysroot/usr/include/bits/syscall.h:23:10: fatal error: 'bits/syscall-32.h' file not found
  |    23 | #include <bits/syscall-32.h>

6.Add do_configure:prepend() function and CFLAGS/CXXFLAGS to fix header file not found issue
  sysdig/0.39.0/sources/sysdig-0.39.0/falcosecurity-libs/userspace/libscap/engine/kmod/scap_kmod.c:30:10: fatal error: driver_config.h: No such file or directory
  |    30 | #include <driver_config.h>

7.Add do_compile:append() function to fix do_package QA Issue

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>