gd: Add patch to fix compiler error about missing const
Gcc complains about:

| ../../sources/gd-2.3.3/src/gd_filename.c: In function 'ftype':
| ../../sources/gd-2.3.3/src/gd_filename.c:99:9: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
|    99 |     ext = strrchr(filename, '.');
|       |         ^
| cc1: all warnings being treated as errors

Even the newest git master commit does not fix this.

Signed-off-by: Jörg Sommer <joerg.sommer@navimatix.de>
Signed-off-by: Khem Raj <raj.khem@gmail.com>